### ISSUE TITLE
NumberVector's data is not a vector?

### ISSUE THREAD

**Issue by lindsayad** [roystgnr/MetaPhysicL#32]
@roystgnr I'm struggling to understand why `NumberArray` and `NumberVector` are essentially the same class, at least upon cursory glance at the class API. I guess I would have assumed that `NumberVector` would store its data in an `std::vector` but it's also a C array like for `NumberArray`. I'm curious about using something with `std::vector` for the underlying storage because then move operations become meaningful (although I may be venturing into the realm of micro-optimization). I know that `DynamicSparseNumberBase` uses `std::vectors` for both the data and indices.

**Comment by roystgnr** [comment]
Gah, did I never get around to answering this?  Sorry!

Don't think std::vector dynamic sizing vs std::array static sizing, think mathematical vector thing-in-a-vector-space vs computational array list-of-disconnected-objects.

The difference is in the behavior of functions_acting_on_vectors(number_object).

If number_object is a NumberVector, then we want to treat it as one mathematical vector.  If you take the outer product of two NumberVector objects a and b of length N, for example, then you should get a single NumberVector-of-NumberVector output of size NxN, entry i,j of which is a[i]*b[j].

If number_object is a NumberArray, then we want to pass any operations straight through to the array contents.  If you take the outer product of two NumberArray objects of length N, then you should get a single NumberArray output of length N, each of whose entries i is the outer product of a[i] and b[i].

**Comment by roystgnr** [comment]
Wow, I was feeling guilty for taking two months to answer, but then you took seven months to *read* the answer?  :laughing:

**Comment by lindsayad** [comment]
Hahaha I definitely read it at the time! But I didn’t really process it until a few days ago :-)
