### ISSUE TITLE
Need std::cbrt for dual numbers (C++11)

### ISSUE THREAD

**Issue by dschwen** [roystgnr/MetaPhysicL#36]
`std::cbrt(x)` is faster and more mnemonic than `std::pow(x, 1.0/3.0)`. Would be nice to have support for it in MetaPhysicL

**Comment by roystgnr** [comment]
There's a whole swath of useful functions that C++11 added and we ought to too, isn't there?

https://en.cppreference.com/w/cpp/numeric/math

There's also a whole swath of pointless alternative names that C++11 added, I guess for easier transitioning from C99, which we should add too for maximum compatibility with preexisting code.

**Comment by roystgnr** [comment]
I'm kind of tempted to procrastinate on anything like remquo that has a call signature too weird to fit into our existing macros, though, at least until we encounter an actual user who wants it.

**Comment by roystgnr** [comment]
Closed by #39
