### ISSUE TITLE
Make check test failure with GCC 7.2

### ISSUE THREAD

**Issue by bboutkov** [roystgnr/MetaPhysicL#4]
As mentioned via email this issue was spotted while I was investigating libMesh projection_matrix related issues and was forced to swap from GCC 6.x to 7.2.

Was getting errors on dualnamedarray.h:80 : 
error: template argument ‘(unsigned int)derivativeindex’ involves template parameter(s)
 struct DerivativeOf<NamedIndexArray<DataVector, SparseSizeVector>, derivativeindex>
when test/instantiations_unit.C and /test/dualnamedarray_unit.C were including the file.

At a cursory glance I can currently get by using the disable_dual_named branch without further complications, but this issue appparently needs to be addressed for later work. As a note, this issue may already have been addressed in C++17, but this needs to be verified once the official standard is available.

**Comment by roystgnr** [comment]
Reopening because this is actually incredibly embarrassingly fixable.
