### ISSUE TITLE
Implicit conversion through a constructor relying on SFINAE confuses the compiler

### ISSUE THREAD

**Issue by dschwen** [roystgnr/MetaPhysicL#70]
`std::is_convertible` over estimates the convertibility of types into dual numbers. This causes compile errors with Eigen, when instantiating Eigen objects on DualNumbers. The fix may be to restrict the 

```
template <typename T2>
DualNumber(const T2& val);
```

with a dash of `enable_if`.

**Comment by lindsayad** [comment]
Can you explain this a little more? We were not using `std::is_convertible` in `DualNumber` before #71 right? Rather you are adding it. Do you just mean that our previous template constructor was overestimating/allowing too much convertability? E.g.
```
template <typename T2>
DualNumber(const T2& val);
```
allowed too many implicit conversions? Now I suppose with your changes from #71 these undesirable implicit conversions will no longer happen in Eigen. What happens instead?

**Comment by dschwen** [comment]
> [..] allowed too many implicit conversions? Now I suppose with your changes from #71 these undesirable implicit conversions will no longer happen in Eigen. What happens instead?

See this discussion on the Eigen issue tracker: https://gitlab.com/libeigen/eigen/-/issues/1902

TBH, I do not fully understand what the compiler is thinking. It is almost like the decision for `std::is_convertible` is based on the constructor declaration rather than the definition. Because that original CTOR would most certainly fail to compile when instantiated with an Eigen::Matrix as `T2`.
